FROM openjdk:8 as builder
WORKDIR /build
COPY ~/.m2/ /root/.m2/
COPY pom.xml /build/pom.xml
COPY mvnw /build/mvnw
COPY .mvn/ /build/.mvn/
COPY src/ /build/src/
RUN ./mvnw dependency:resolve

FROM openjdk:8 	
EXPOSE 8080
COPY --from=builder /build/ /
COPY --from=builder /root/.m2/ /root/.m2/
ENTRYPOINT ["./mvnw","spring-boot:run"]