FROM maven:3.3-jdk-8 as builder
WORKDIR '/'
COPY pom.xml /tmp/pom.xml
RUN mvn -B -f /tmp/pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
COPY . .
RUN mvn -s /usr/share/maven/ref/settings-docker.xml clean package

FROM openjdk:8 	
EXPOSE 8080
COPY --from=builder /target /
#CMD ["java", "-jar", "logistica.jar"]